### ISSUE TITLE
Source of tiles?

### ISSUE THREAD

**Issue by mrgloom** [CreativeInquiry/terrapattern#5]
Hello, guys! Good job!

I have some questions:
1. I'm trying to figure out what source of tiles you are using? is it Google Maps? What terms of use of it? 
2. Can you explain why you are using CoverTree algorithm(pros and cons)? On what type of data ? a float feature vector from CNN output?

Also as suggestion related to 2nd question you can look at https://github.com/mrgloom/Dancing-around-hamming-distance for methods of generation binary vectors instead of float vectors, so Hamming Distance can be used instead of Euclidean.

**Comment by golanlevin** [comment]
Hello mrgloom, 
As you can see, for the interactive front-end slippy map, our website is linking through to Google's map tile servers. For analyzing the terrain via CNN there are a number of different sources one could use, such as Mapbox Satellite, Bing, Digital Globe, etc.
For K-Nearest Neighbor search through the CNN's float feature vectors, we initially tried a naive linear search, but search times were approximately ~30 seconds, so naturally we sought something faster. We initially tried the Ball Tree, which was very fast, but we instead chose to use the CoverTree for our web-server because it could handle asynchronous (multi-threaded) simultaneous requests. Our search times are now generally ~100ms.
